apiVersion: apps/v1
kind: Deployment
metadata:
  name: zack-fleet-test
  labels:
    app: zack-fleet-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zack-fleet-test
  template:
    metadata:
      labels:
        app: zack-fleet-test
    spec:
      containers:
        - name: zack-fleet-test
          image: nginx:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
